### PR TITLE
Adding TurnOpt to the leaderboard

### PR DESCRIPTION
**Pull request by LiatB282**

### CODE REVIEW

**Comment by yuchenlin** [comment]
Hi Liat,

The evaluation result is as follows! It's even better than human lower bound! Congrats! Would you please add a runnable script in this PR or another one, so we can run and verify the performance? Also, it will be much better if you'd like to share a link that can tell people more information about TurnOpt? (say, what model is it based on? Is it gpt-4 prompting?) Thanks! :D 

| model                      |   len |   cover |   pos |   win_tie |   overall |
|----------------------------|-------|---------|-------|-----------|-----------|
| human (upper bound)        | 12.84 |   99.00 | 98.11 |    100.00 |     97.13 |
| TurnOpt                    | 14.24 |  100.00 | 99.56 |     49.44 |     49.22 |
| human (lower bound)        | 12.84 |   99.00 | 98.11 |     50.00 |     48.56 |
| gpt-4-0613                 | 14.13 |   97.44 | 91.78 |     50.44 |     45.11 |
| gpt-4-1106-preview         | 14.90 |   96.33 | 90.11 |     50.78 |     44.08 |
| gpt-3.5-turbo              | 12.76 |   92.11 | 83.00 |     49.78 |     38.06 |
| Yi-34b-chat                | 13.45 |   80.11 | 75.11 |     39.44 |     23.73 |
| Pallas-0.5                 | 14.83 |   86.67 | 79.56 |     32.22 |     22.22 |
| vicuna-13b-v1.5            | 15.02 |   85.89 | 79.56 |     27.44 |     18.75 |
| tulu-2-dpo-70b             | 17.89 |   88.78 | 80.11 |     23.00 |     16.36 |
| Mixtral-8x7B-Instruct-v0.1 | 20.15 |   84.11 | 73.33 |     17.89 |     11.03 |
| Llama-2-7b-chat-hf         | 16.06 |   88.56 | 76.44 |     15.44 |     10.45 |
| zephyr-7b-beta             | 15.76 |   82.44 | 72.78 |     16.89 |     10.13 |
| Yi-6b-chat                 | 13.32 |   71.67 | 63.56 |     22.11 |     10.07 |

**Comment by LiatB282** [comment]
Many thanks for running this! We are preparing a writeup where we can provide more details. Our approach uses GPT4 with some notion of critiques.

**Comment by Mihaiii** [comment]
@yuchenlin How do you calculate PoS, though?
This model says: "The farmer sits on a stool to milk the cow, carefully pulling on its utter."

But I think it uses "utter" with the meaning of "udder" and therefore "utter" is completely misplaced. But it still is the model with highes PoS: 99.56 .

And this is the first/only example I looked over because I remember it from the time I also ran it for Pallas-0.5 .

**Comment by yuchenlin** [comment]
@Mihaiii  thanks for letting me know. I'll double check the eval script. The related lines are: https://github.com/allenai/CommonGen-Eval/blob/448741b2a75768bf2648e4ba19ab0761c2646a37/show_table.py#L92

**Pull request merged**
